on:
  push:

jobs:
  delete-debug:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: Get_feature_branch
        id: ticket_no
        uses: actions/github-script@v6
        env:
          BASE_BRANCH_NAME: ${{github.base_ref}}
        with:
          result-encoding: string
          script: |
            let base_ref = "develop_JMAS/2022/SCRUM-TEST"
            let base_ref_ary = base_ref.split('/')
            let developer_ary = base_ref_ary.shift().split('_')
            let developer = developer_ary.pop()
            let year = base_ref_ary.shift()
            let ticket_no = base_ref_ary.shift()
            let feature_branch = 'feature/' + developer + '/' + year + '/' + ticket_no
            console.log("削除対象ブランチ："+feature_branch)
            return feature_branch

      - name: Checkout
        uses: actions/checkout@v3

      - name:  Exsit_feature_branch
        continue-on-error: true
        env:
          BRANCH_NAME: ${{ steps.ticket_no.outputs.result }}
        run: |
        
          branch_is_existing=$(
            git fetch origin ${BRANCH_NAME} &&
            echo true ||
            echo false
          )
          echo "BRANCH_IS_EXISTING=${branch_is_existing}" >> $GITHUB_ENV
          echo "FEATURE_BRANCH=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Delete_feature_branch
        if: env.BRANCH_IS_EXISTING == 'true'
        run: |
        
          branch_is_deleted=$(
            git push origin --delete develop_JMAS/2022/SCRUM-TEST2 &&
            echo true ||
            echo false
          )          
          echo "BRANCH_IS_DELETED=${branch_is_deleted}" >> $GITHUB_ENV

      - name: Delete Success
        if: env.BRANCH_IS_DELETED == 'true'
        run: |
          echo ${BRANCH_NAME}
          echo "ブランチの削除に成功しました"

      - name: Delete Failure
        if: env.BRANCH_IS_DELETED == 'false'
        run: |
          echo ${BRANCH_NAME}
          echo "::error::ブランチの削除に失敗しました"
