
name: debug

on:
  push:
    branches:
    # スクラムチーム内で試験運用
    - 'feature/JMAS/202[0-9]/SCRUM-**'
    - 'feature/DIP/202[0-9]/SCRUM-**'

jobs:
  debug:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    
    env:
      GH_TOKEN: ${{ github.token }}
    
    steps:
      - name: Get develop branch
        id: dev_branch
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: |
            const ref = "${{github.ref_name}}"
            const refs = ref.split('/')
            const ticket_no = refs.pop()
            const year = refs.pop()
            const developer = refs.pop()
            const develop_branch = 'develop_' + developer + '/' + year + '/' + ticket_no
            console.log("作成対象ブランチ："+develop_branch)
            return develop_branch

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name:  Exsit develop branch
        continue-on-error: true
        id: exsit
        env:
          DEVELOP_BRANCH: ${{ steps.dev_branch.outputs.result }}
        run: |
          git fetch origin ${{ env.DEVELOP_BRANCH }}

      - name: Create develop branch
        if: ${{ steps.exsit.outcome == 'failure' }}
        env:
          DEVELOP_BRANCH: ${{ steps.dev_branch.outputs.result }}
        run: |
          git config user.email "action@github.com"
          git config user.name "github actions"
          git checkout -b ${{ env.DEVELOP_BRANCH }} remotes/origin/main
          git push origin ${{ env.DEVELOP_BRANCH }}

      - name: Get Ticket No
        if: ${{ steps.exsit.outcome == 'failure' }}
        id: ticket_no
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: |
            const ref = "${{github.ref_name}}"
            const refs = ref.split('/')
            const ticket_no = refs.pop()
            return ticket_no

      - name: Create pr
        if: ${{ steps.exsit.outcome == 'failure' }}
        env:
          DEVELOP_BRANCH: ${{ steps.dev_branch.outputs.result }}
          TICKET_NO: ${{ steps.ticket_no.outputs.result }}
        run: |
          gh pr create -base ${{ env.DEVELOP_BRANCH }} -t "【${{ env.TICKET_NO }}】" -b ""
