
name: debug

on:
  push:
    branches:
    # スクラムチーム内で試験運用
    - 'feature/JMAS/202[0-9]/SCRUM-**'
    - 'feature/DIP/202[0-9]/SCRUM-**'

jobs:
  debug:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: Get develop branch
        id: ticket_no
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: |
            console.log("${{github.ref_name}}")
            console.log("feature/JMAS/2022/SCRUM-502")
            const ref = "${{github.ref_name}}"
            const refs = ref.split('/')
            const ticket_no = refs.pop()
            const year = refs.pop()
            const developer = refs.pop()
            const develop_branch = 'develop_' + developer + '/' + year + '/' + ticket_no
            console.log("対象ブランチ："+develop_branch)
            return develop_branch

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name:  Exsit develop branch
        continue-on-error: true
        id: exsit
        env:
          DEVELOP_BRANCH: ${{ steps.ticket_no.outputs.result }}
        run: |
          git config --global user.email "xxxxx@xxx.com"
          git config --global user.name "github actions"
          git fetch origin ${{ env.DEVELOP_BRANCH }}

      - name: Create develop branch
        if: ${{ steps.exsit.outcome == 'failure' }}
        env:
          DEVELOP_BRANCH: ${{ steps.ticket_no.outputs.result }}
        run: |
          git checkout -b ${{ env.DEVELOP_BRANCH }} remotes/origin/main
          git push origin ${{ env.DEVELOP_BRANCH }}

      - name: Marge develop branch
        if: ${{ steps.exsit.outcome == 'success' }}
        env:
          DEVELOP_BRANCH: ${{ steps.ticket_no.outputs.result }}
        run: |
          git switch ${{ env.DEVELOP_BRANCH }}
          git merge remotes/origin/main
          git push origin ${{ env.DEVELOP_BRANCH }}
