on:
  pull_request:
    types: [closed]

jobs:
  debug:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.merged == true
    timeout-minutes: 3
    steps:
      - name: Print branch name
        env:
          HEAD_BRANCH_NAME: ${{github.head_ref}}
          BASE_BRANCH_NAME: ${{github.base_ref}}
        run: echo "HEAD_BRANCH_NAME = [".$BRANCH_NAME."], BASE_BRANCH_NAME = [".$BASE_BRANCH_NAME."]"
