on:
  push:

jobs:
  debug:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - uses: actions/github-script@v6
        env:
          FIRST_NAME: ${{github.base_ref}}
          LAST_NAME: ${{github.head_ref}}
        with:
          script: |
            const { FIRST_NAME, LAST_NAME } = process.env

            console.log(`Hello ${FIRST_NAME} ${LAST_NAME}`)
            
            return ${FIRST_NAME}

      - name:  show_ticket_name
        run: echo "${{steps.set-result.outputs.result}}"
