on:
  push:

jobs:
  debug:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: get_ticket
        id: ticket_no
        uses: actions/github-script@v6
        env:
          BASE_BRANCH_NAME: ${{github.base_ref}}
        with:
          result-encoding: string
          script: |
            let base_ref = "develop_JMAS/2022/SCRUM-502"
            let base_ref_ary = base_ref.split('/')
            let developer_ary = base_ref_ary.shift().split('_')
            let developer = developer_ary.pop()
            let year = base_ref_ary.shift()
            let ticket_no = base_ref_ary.shift()
            return 'feature/' + developer + '/' + year + '/' + ticket_no
      
      - name: Checkout
        uses: actions/checkout@v3
      - name:  show_ticket
        env:
          TARGET_BRANCH: ${{ steps.ticket_no.outputs.result }}
        run: |
          branch_is_existing=$(
            git fetch origin ${TARGET_BRANCH} &&
            echo true ||
            echo false
          )

          if (${branch_is_existing} == 'true') {
            echo "ok"
          } else {
            echo "ng"
          }
