on:
  push:

jobs:
  debug:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: get_ticket_name
        env:
          BASE_BRANCH_NAME: ${{github.base_ref}}
        uses: actions/github-script@v6
        id: set-result
        with:
          result-encoding: string
          script: |
            return BASE_BRANCH_NAME;

      - name:  show_ticket_name
        run: echo "${{steps.set-result.outputs.result}}"
