on:
  push:

jobs:
  debug:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: get_ticket
        id: ticket_no
        uses: actions/github-script@v6
        env:
          BASE_BRANCH_NAME: ${{github.base_ref}}
        with:
          result-encoding: string
          script: |
            const { BASE_BRANCH_NAME } = process.env
            console.log(`Hello ${BASE_BRANCH_NAME}`)
            console.log(process.env)
            console.log(BASE_BRANCH_NAME)
            let base_ref = "develop_JMAS/2022/SCRUM_502"
            let base_ref_ary = base_ref.split('/')
            return base_ref_ary.pop()
      
      - name:  show_ticket
        env:
          RETURN_CONTEXT2: ${{ steps.ticket_no.outputs.result }}
        run: echo "$RETURN_CONTEXT2"
