on:
  push:

jobs:
  debug:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: get_ticket
        id: ticket_no
        uses: actions/github-script@v6
        env:
          BASE_BRANCH_NAME: ${{github.base_ref}}
        with:
          result-encoding: array
          script: |
            let base_ref = "develop_JMAS/2022/SCRUM_502"
            let base_ref_ary = base_ref.split('/')
            let developer_ary = base_ref_ary.shift().split('_')
            let developer = developer_ary.pop()
            let year = base_ref_ary.shift()
            let ticket_no = base_ref_ary.shift()/JMAS/2022/SCRUM-502
            let target_branch = 'feature/' + developer + '/' + year + '/' + ticket_no
            return target_branch
      
      - name:  show_ticket
        env:
          RETURN_CONTEXT2: ${{ steps.ticket_no.outputs.result }}
        run: echo "$RETURN_CONTEXT2"
